runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8.2"
  document_root: web

resources:
  cpu: 1
  memory_gb: 4

# Automatic scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 150
  cpu_utilization:
    target_utilization: 0.60
